### PR TITLE
Custom messages

### LINKED ISSUE #4: Allow custom messages
Hi,

how about allowing an optional custom message in `st.fails()`, `st.succeeds()`, `st.exitCode()`, etc.? Just like *tape* allows them in every type of assertion – including simple ones like [`t.pass()`](https://github.com/substack/tape/tree/b235fce183f0e95b3e55ee32ae193c4b232c09f6#tpassmsg).

### PR DESCRIPTION
**Pull request by tomekwi**
Closes #4

### CODE REVIEW

**Comment by tomekwi** [comment]
Two heads-ups though:

* I’ve no idea how to test the updates in the current test suite. I’ve tested it in the wild on [a project I use *tape-spawn* in](//github.com/studio-b12/doxie). I’d leave it as it is because there’s nothing that could possibly go wrong.

* I haven’t touched `StreamTest.prototype.empty` and `StreamTest.prototype.match` because I don’t quite get the idea of `failMessage`. In *tape* I’ve only ever used one message per assertion whether it fails or succeeds.

**Comment by tomekwi** [comment]
:checkered_flag:

**Comment by maxogden** [comment]
awesome thanks! yes the `failMessage` is a little weird... it is currently there to handle the case where the output did not match but you want the failure message to say something specific instead of just `did not match`.

If it passes it uses `message`, if it fails it uses `failMessage` which includes the entire output buffer, mostly because `.match` succeeds I didn't want it to print out the entire output buffer. I am open to suggestions on making this better. Maybe in the event of a failure it can just append the output buffer to the end of `message` and then we could get rid of `failMessage`

**Comment by maxogden** [comment]
published as 1.4.0

**Comment by tomekwi** [comment]
Thanks for publishing! I’ve opened https://github.com/maxogden/tape-spawn/issues/8 to think about the `failMessage` thing.

**Pull request merged**
